(in-package :cl-user)

(load "package.lisp")
(load "defun.lisp")
(load "bootstrap.lisp")
(load "defmacro.lisp")
(load "macros.lisp")
(load "let.lisp")
(load "flet-and-labels.lisp")
(load "conditionals.lisp")
(load "loops.lisp")
(load "values.lisp")
(load "sequence.lisp")
(load "math.lisp")
(load "error.lisp")
(load "streams.lisp")
(load "readtable.lisp")
(load "reader.lisp")
(load "backquote.lisp")

